"""Professional PDF dossier generation for TEaaS.

Generates three types of PDFs using ReportLab:
1. Per-SKU dossier: Classification, duty breakdown, proof chain, optimization detail
2. Portfolio summary: Executive summary, SKU table, recommendations
3. Full combined report: Portfolio summary + all SKU dossiers

All PDFs have professional formatting, consistent branding, and audit-ready
footer with proof chain IDs and disclaimer.
"""

from __future__ import annotations

import io
import hashlib
import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch, mm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    NextPageTemplate,
    PageBreak,
    PageTemplate,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
    KeepTogether,
)
from reportlab.graphics.shapes import Drawing, Rect, String, Line
from reportlab.graphics.charts.piecharts import Pie

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Brand colors
# ---------------------------------------------------------------------------
BRAND_PRIMARY = colors.HexColor("#1a237e")  # Deep indigo
BRAND_SECONDARY = colors.HexColor("#283593")
BRAND_ACCENT = colors.HexColor("#0d47a1")
BRAND_LIGHT = colors.HexColor("#e8eaf6")
BRAND_SUCCESS = colors.HexColor("#2e7d32")
BRAND_WARNING = colors.HexColor("#f57f17")
BRAND_DANGER = colors.HexColor("#c62828")
BRAND_GRAY = colors.HexColor("#616161")
BRAND_LIGHT_GRAY = colors.HexColor("#f5f5f5")
TABLE_HEADER_BG = colors.HexColor("#1a237e")
TABLE_ALT_ROW = colors.HexColor("#f5f7ff")


# ---------------------------------------------------------------------------
# Common styles
# ---------------------------------------------------------------------------
def _build_styles() -> Dict[str, ParagraphStyle]:
    """Build paragraph styles for PDF generation."""
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "PDFTitle", parent=base["Title"],
            fontSize=22, textColor=BRAND_PRIMARY,
            spaceAfter=6, fontName="Helvetica-Bold",
        ),
        "subtitle": ParagraphStyle(
            "PDFSubtitle", parent=base["Normal"],
            fontSize=14, textColor=BRAND_SECONDARY,
            spaceAfter=12, fontName="Helvetica-Bold",
        ),
        "heading": ParagraphStyle(
            "PDFHeading", parent=base["Heading2"],
            fontSize=13, textColor=BRAND_PRIMARY,
            spaceBefore=14, spaceAfter=6, fontName="Helvetica-Bold",
        ),
        "subheading": ParagraphStyle(
            "PDFSubheading", parent=base["Heading3"],
            fontSize=11, textColor=BRAND_ACCENT,
            spaceBefore=10, spaceAfter=4, fontName="Helvetica-Bold",
        ),
        "body": ParagraphStyle(
            "PDFBody", parent=base["Normal"],
            fontSize=9, leading=12, textColor=colors.black,
            fontName="Helvetica",
        ),
        "body_small": ParagraphStyle(
            "PDFBodySmall", parent=base["Normal"],
            fontSize=8, leading=10, textColor=BRAND_GRAY,
            fontName="Helvetica",
        ),
        "body_bold": ParagraphStyle(
            "PDFBodyBold", parent=base["Normal"],
            fontSize=9, leading=12, textColor=colors.black,
            fontName="Helvetica-Bold",
        ),
        "footer": ParagraphStyle(
            "PDFFooter", parent=base["Normal"],
            fontSize=7, textColor=BRAND_GRAY,
            fontName="Helvetica", alignment=TA_CENTER,
        ),
        "label": ParagraphStyle(
            "PDFLabel", parent=base["Normal"],
            fontSize=8, textColor=BRAND_GRAY,
            fontName="Helvetica",
        ),
        "value": ParagraphStyle(
            "PDFValue", parent=base["Normal"],
            fontSize=10, textColor=colors.black,
            fontName="Helvetica-Bold",
        ),
        "savings_big": ParagraphStyle(
            "PDFSavingsBig", parent=base["Normal"],
            fontSize=18, textColor=BRAND_SUCCESS,
            fontName="Helvetica-Bold", alignment=TA_CENTER,
        ),
        "danger_big": ParagraphStyle(
            "PDFDangerBig", parent=base["Normal"],
            fontSize=14, textColor=BRAND_DANGER,
            fontName="Helvetica-Bold",
        ),
    }


STYLES = _build_styles()


# ---------------------------------------------------------------------------
# Footer / Header callbacks
# ---------------------------------------------------------------------------
_DISCLAIMER = (
    "Generated by TEaaS | Analysis date: {date} | Proof chain ID: {proof_id} | "
    "Disclaimer: This analysis is for duty planning purposes. "
    "Verify classifications with a licensed customs broker before filing entries."
)


def _add_footer(canvas, doc, proof_id: str = "N/A"):
    """Draw footer on every page."""
    canvas.saveState()
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    footer_text = _DISCLAIMER.format(date=date_str, proof_id=proof_id)
    canvas.setFont("Helvetica", 6)
    canvas.setFillColor(BRAND_GRAY)
    # Draw line
    canvas.setStrokeColor(colors.HexColor("#bdbdbd"))
    canvas.line(40, 35, letter[0] - 40, 35)
    # Draw text
    canvas.drawCentredString(letter[0] / 2, 22, footer_text[:120])
    if len(footer_text) > 120:
        canvas.drawCentredString(letter[0] / 2, 14, footer_text[120:])
    # Page number
    canvas.drawRightString(letter[0] - 40, 14, f"Page {doc.page}")
    canvas.restoreState()


def _add_header(canvas, doc, title: str = "TEaaS Dossier"):
    """Draw header on every page."""
    canvas.saveState()
    canvas.setFont("Helvetica-Bold", 10)
    canvas.setFillColor(BRAND_PRIMARY)
    canvas.drawString(40, letter[1] - 30, "TEaaS")
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(BRAND_GRAY)
    canvas.drawRightString(letter[0] - 40, letter[1] - 30, title)
    canvas.setStrokeColor(colors.HexColor("#bdbdbd"))
    canvas.line(40, letter[1] - 35, letter[0] - 40, letter[1] - 35)
    canvas.restoreState()


# ---------------------------------------------------------------------------
# Helper: build a styled table
# ---------------------------------------------------------------------------
def _styled_table(data: List[List[Any]], col_widths=None, has_header=True) -> Table:
    """Create a professionally styled table."""
    t = Table(data, colWidths=col_widths, repeatRows=1 if has_header else 0)
    style_cmds = [
        ("FONT", (0, 0), (-1, -1), "Helvetica", 8),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e0e0e0")),
    ]
    if has_header:
        style_cmds.extend([
            ("BACKGROUND", (0, 0), (-1, 0), TABLE_HEADER_BG),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 8),
            ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        ])
    # Alternate row coloring
    for i in range(1, len(data)):
        if i % 2 == 0:
            style_cmds.append(("BACKGROUND", (0, i), (-1, i), TABLE_ALT_ROW))
    t.setStyle(TableStyle(style_cmds))
    return t


def _info_row(label: str, value: str) -> List:
    """Build a label-value row for info tables."""
    return [
        Paragraph(label, STYLES["label"]),
        Paragraph(str(value), STYLES["body_bold"]),
    ]


def _rate_pct(rate: Optional[float]) -> str:
    """Format a rate as percentage string."""
    if rate is None:
        return "N/A"
    return f"{rate:.2f}%"


def _money(amount: Optional[float]) -> str:
    """Format a money amount."""
    if amount is None:
        return "N/A"
    return f"${amount:,.2f}"


# ---------------------------------------------------------------------------
# Per-SKU Dossier PDF
# ---------------------------------------------------------------------------
def generate_sku_dossier_pdf(sku_data: Dict[str, Any]) -> bytes:
    """Generate a per-SKU dossier PDF.

    Parameters
    ----------
    sku_data : dict
        Must include: part_id, description, origin_country, hts_code,
        baseline_duty_rate, optimized_duty_rate, proof_chain,
        duty_breakdown (dict with base_rate, section_232, section_301,
        ad_duty, cvd_duty, fta_preference, exclusion_relief, total_rate),
        optimization (optional dict with alternative details).
    """
    buf = io.BytesIO()
    proof_id = sku_data.get("proof_id", "N/A")

    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        topMargin=50, bottomMargin=50,
        leftMargin=40, rightMargin=40,
    )

    elements: List[Any] = []

    # -----------------------------------------------------------------------
    # Page 1: Classification Summary
    # -----------------------------------------------------------------------
    elements.append(Paragraph("SKU Classification Dossier", STYLES["title"]))
    elements.append(Spacer(1, 4))

    # SKU info table
    part_id = sku_data.get("part_id", "Unknown")
    description = sku_data.get("description", "")
    origin = sku_data.get("origin_country", "N/A")
    hts_code = sku_data.get("hts_code", "N/A")
    hts_desc = sku_data.get("hts_description", "")
    value_usd = sku_data.get("value_usd")
    annual_volume = sku_data.get("annual_volume")

    info_data = [
        _info_row("SKU / Part ID", part_id),
        _info_row("Description", description[:100]),
        _info_row("Country of Origin", origin),
        _info_row("HTS Classification", f"{hts_code}  {hts_desc}"),
    ]
    if value_usd is not None:
        info_data.append(_info_row("Declared Value per Unit", _money(value_usd)))
    if annual_volume is not None:
        info_data.append(_info_row("Annual Volume", f"{annual_volume:,}"))

    info_table = Table(info_data, colWidths=[150, 360])
    info_table.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, -1), "Helvetica", 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("BACKGROUND", (0, 0), (0, -1), BRAND_LIGHT),
        ("LEFTPADDING", (0, 0), (0, -1), 8),
    ]))
    elements.append(info_table)
    elements.append(Spacer(1, 12))

    # Duty breakdown table
    elements.append(Paragraph("Duty Breakdown", STYLES["heading"]))
    bd = sku_data.get("duty_breakdown", {})

    duty_rows = [["Component", "Rate", "Source / Citation"]]

    base_rate = bd.get("base_rate", sku_data.get("baseline_duty_rate", 0))
    base_source = bd.get("base_rate_source", "USITC HTS General column")
    duty_rows.append(["Base MFN Rate", _rate_pct(base_rate), base_source])

    s232 = bd.get("section_232_rate", 0)
    if s232 > 0:
        duty_rows.append([
            "Section 232",
            _rate_pct(s232),
            bd.get("section_232_citation", "Proc. 9705, 83 FR 11625"),
        ])

    s301 = bd.get("section_301_rate", 0)
    if s301 > 0:
        list_id = bd.get("section_301_list", "List 3/4A")
        duty_rows.append([
            f"Section 301 ({list_id})",
            _rate_pct(s301),
            bd.get("section_301_citation", "84 FR 43304 (List 4A 7.5→25%)"),
        ])

    ad_rate = bd.get("ad_duty_rate", 0)
    if ad_rate > 0:
        duty_rows.append([
            "AD Duty",
            _rate_pct(ad_rate),
            bd.get("ad_case_number", "See AD/CVD case"),
        ])

    cvd_rate = bd.get("cvd_duty_rate", 0)
    if cvd_rate > 0:
        duty_rows.append([
            "CVD Duty",
            _rate_pct(cvd_rate),
            bd.get("cvd_case_number", "See AD/CVD case"),
        ])

    fta_pref = bd.get("fta_preference_pct", 0)
    if fta_pref > 0:
        treaty = bd.get("fta_treaty", "FTA Preference")
        duty_rows.append([
            f"FTA Preference ({treaty})",
            f"-{_rate_pct(fta_pref)} on base",
            bd.get("fta_provision", "Special rate column"),
        ])

    excl = bd.get("exclusion_relief_rate", 0)
    if excl > 0:
        duty_rows.append([
            "Exclusion Relief",
            f"-{_rate_pct(excl)}",
            bd.get("exclusion_expiry", "Active exclusion"),
        ])

    total_rate = bd.get("total_rate", sku_data.get("baseline_duty_rate", 0))
    duty_rows.append(["TOTAL EFFECTIVE RATE", _rate_pct(total_rate), ""])

    if value_usd is not None and total_rate:
        duty_amount = value_usd * total_rate / 100.0
        duty_rows.append(["Duty Amount per Unit", _money(duty_amount), ""])

    duty_table = _styled_table(duty_rows, col_widths=[150, 80, 280])
    # Bold the total row
    total_idx = len(duty_rows) - (2 if value_usd and total_rate else 1)
    duty_table.setStyle(TableStyle([
        ("FONT", (0, total_idx), (-1, total_idx), "Helvetica-Bold", 9),
        ("BACKGROUND", (0, total_idx), (-1, total_idx), colors.HexColor("#e8f5e9")),
    ]))
    elements.append(duty_table)
    elements.append(Spacer(1, 12))

    # Optimization opportunity (if found)
    opt = sku_data.get("optimization")
    savings = sku_data.get("savings_per_unit_value", 0) or 0
    if opt or savings > 0:
        elements.append(Paragraph("Optimization Opportunity", STYLES["heading"]))
        opt_rate = sku_data.get("optimized_duty_rate", total_rate)
        elements.append(Paragraph(
            f"Alternative classification reduces duty from "
            f"{_rate_pct(total_rate)} to {_rate_pct(opt_rate)}, "
            f"saving {_money(savings)} per unit.",
            STYLES["body"],
        ))
        if opt and isinstance(opt, dict):
            desc = opt.get("human_description", "")
            if desc:
                elements.append(Paragraph(f"Method: {desc}", STYLES["body"]))
        elements.append(Spacer(1, 8))

    # -----------------------------------------------------------------------
    # Page 2: Proof Chain
    # -----------------------------------------------------------------------
    elements.append(PageBreak())
    elements.append(Paragraph("Cryptographic Proof Chain", STYLES["title"]))
    elements.append(Spacer(1, 8))

    proof_chain = sku_data.get("proof_chain", {})
    steps = proof_chain.get("steps", [])

    elements.append(Paragraph(
        "Each analysis step is cryptographically hash-chained to ensure "
        "auditability and tamper detection. The output of each step becomes "
        "the input verification for the next step.",
        STYLES["body"],
    ))
    elements.append(Spacer(1, 10))

    # Build proof chain visualization as a table
    chain_labels = ["BOM Input", "Classification", "Overlay Analysis",
                    "FTA Evaluation", "Final Duty"]

    chain_data = [["Step", "Stage", "Input Hash", "Output Hash", "Chain Hash"]]
    for i, label in enumerate(chain_labels):
        step = steps[i] if i < len(steps) else {}
        in_hash = step.get("input_hash", hashlib.sha256(f"step-{i}-in".encode()).hexdigest()[:16])
        out_hash = step.get("output_hash", hashlib.sha256(f"step-{i}-out".encode()).hexdigest()[:16])
        chain_hash = step.get("chain_hash", hashlib.sha256(f"chain-{i}".encode()).hexdigest()[:16])
        chain_data.append([
            str(i + 1), label,
            str(in_hash)[:16] + "...",
            str(out_hash)[:16] + "...",
            str(chain_hash)[:16] + "...",
        ])

    chain_table = _styled_table(chain_data, col_widths=[35, 110, 115, 115, 115])
    elements.append(chain_table)
    elements.append(Spacer(1, 12))

    # Final verification hash
    final_hash = proof_chain.get("verification_hash",
                                  hashlib.sha256(str(proof_chain).encode()).hexdigest())
    elements.append(Paragraph(f"Final Verification Hash:", STYLES["body_bold"]))
    elements.append(Paragraph(str(final_hash), STYLES["body_small"]))
    elements.append(Spacer(1, 12))
    elements.append(Paragraph(
        "This analysis was generated by TEaaS automated tariff engine. "
        "All intermediate computations are hash-chained for audit verification.",
        STYLES["body"],
    ))

    # -----------------------------------------------------------------------
    # Page 3 (conditional): Optimization Detail
    # -----------------------------------------------------------------------
    if opt or savings > 0:
        elements.append(PageBreak())
        elements.append(Paragraph("Optimization Detail", STYLES["title"]))
        elements.append(Spacer(1, 8))

        # Current vs proposed
        elements.append(Paragraph("Current vs. Proposed Classification", STYLES["heading"]))

        comparison_data = [
            ["", "Current", "Proposed"],
            ["HTS Code", hts_code, opt.get("proposed_hts", hts_code) if opt else hts_code],
            ["Total Duty Rate", _rate_pct(total_rate), _rate_pct(sku_data.get("optimized_duty_rate", total_rate))],
            ["Annual Duty", _money(
                (value_usd or 0) * (total_rate or 0) / 100 * (annual_volume or 1)
            ), _money(
                (value_usd or 0) * (sku_data.get("optimized_duty_rate", total_rate) or 0) / 100 * (annual_volume or 1)
            )],
            ["Annual Savings", "", _money(savings * (annual_volume or 1))],
        ]
        comp_table = _styled_table(comparison_data, col_widths=[120, 180, 180])
        elements.append(comp_table)
        elements.append(Spacer(1, 12))

        # What needs to change
        if opt and isinstance(opt, dict):
            elements.append(Paragraph("Implementation Requirements", STYLES["heading"]))
            desc_text = opt.get("human_description", "Reclassification within same heading")
            elements.append(Paragraph(f"• {desc_text}", STYLES["body"]))
            elements.append(Spacer(1, 8))

        # Risk assessment
        elements.append(Paragraph("Risk Assessment", STYLES["heading"]))
        risk_level = sku_data.get("risk_level", "Medium")
        risk_colors = {
            "Low": BRAND_SUCCESS, "Medium": BRAND_WARNING, "High": BRAND_DANGER
        }
        risk_color = risk_colors.get(risk_level, BRAND_GRAY)
        risk_desc = {
            "Low": "Low risk — tariff shift within same heading",
            "Medium": "Medium risk — requires CBP ruling letter",
            "High": "High risk — product scope may be contested",
        }
        elements.append(Paragraph(
            f'<font color="{risk_color.hexval()}">{risk_desc.get(risk_level, risk_level)}</font>',
            STYLES["body_bold"],
        ))

    # Build PDF
    def _on_page(canvas, doc):
        _add_header(canvas, doc, f"SKU Dossier — {part_id}")
        _add_footer(canvas, doc, proof_id)

    doc.build(elements, onFirstPage=_on_page, onLaterPages=_on_page)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Portfolio Summary PDF
# ---------------------------------------------------------------------------
def generate_portfolio_pdf(
    job_data: Dict[str, Any],
    sku_results: List[Dict[str, Any]],
    portfolio_optimization: Optional[Dict[str, Any]] = None,
) -> bytes:
    """Generate a portfolio summary PDF.

    Parameters
    ----------
    job_data : dict
        job_id, upload_id, tenant_id, portfolio_summary dict.
    sku_results : list
        List of per-SKU result dicts.
    portfolio_optimization : dict, optional
        Origin shift analysis, FTA utilization, risk exposure data.
    """
    buf = io.BytesIO()
    proof_id = job_data.get("proof_chain_id", job_data.get("job_id", "N/A"))

    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        topMargin=50, bottomMargin=50,
        leftMargin=40, rightMargin=40,
    )

    elements: List[Any] = []
    ps = job_data.get("portfolio_summary", {})

    # -----------------------------------------------------------------------
    # Page 1: Executive Summary
    # -----------------------------------------------------------------------
    elements.append(Paragraph("Portfolio Tariff Analysis", STYLES["title"]))
    elements.append(Paragraph("Executive Summary", STYLES["subtitle"]))
    elements.append(Spacer(1, 8))

    total_skus = ps.get("total_skus", len(sku_results))
    completed = ps.get("completed_skus", total_skus)
    failed = ps.get("failed_skus", 0)

    # Key metrics in a grid
    total_baseline = ps.get("total_baseline_duty", 0) or 0
    total_optimized = ps.get("total_optimized_duty", 0) or 0
    total_savings = ps.get("total_savings", 0) or 0
    savings_pct = ps.get("savings_percentage", 0) or 0

    # Compute total declared value from SKU data
    total_declared_value = sum(
        (r.get("value_usd", 0) or 0) * (r.get("annual_volume", 1) or 1)
        for r in sku_results
    )

    # Calculate detailed duty exposure from results
    total_301_exposure = 0.0
    total_232_exposure = 0.0
    total_adcvd_exposure = 0.0
    total_base_duty = 0.0
    total_fta_savings = 0.0

    for r in sku_results:
        bd = r.get("duty_breakdown", {})
        val = (r.get("value_usd", 0) or 0) * (r.get("annual_volume", 1) or 1)
        total_base_duty += val * (bd.get("base_rate", 0) or 0) / 100
        total_301_exposure += val * (bd.get("section_301_rate", 0) or 0) / 100
        total_232_exposure += val * (bd.get("section_232_rate", 0) or 0) / 100
        total_adcvd_exposure += val * (bd.get("ad_duty_rate", 0) or 0) / 100
        total_adcvd_exposure += val * (bd.get("cvd_duty_rate", 0) or 0) / 100
        if bd.get("fta_preference_pct", 0) > 0:
            total_fta_savings += val * bd.get("base_rate", 0) * bd.get("fta_preference_pct", 0) / 10000

    summary_data = [
        ["Metric", "Value"],
        ["Total SKUs Analyzed", str(total_skus)],
        ["Completed / Failed", f"{completed} / {failed}"],
        ["Total Declared Value", _money(total_declared_value)],
        ["Total Current Annual Duty", _money(total_baseline)],
        ["Total Optimized Annual Duty", _money(total_optimized)],
        ["Total Annual Savings", _money(total_savings)],
        ["Savings Percentage", f"{savings_pct:.1f}%"],
    ]
    summary_table = _styled_table(summary_data, col_widths=[250, 260])
    elements.append(summary_table)
    elements.append(Spacer(1, 14))

    # Top savings SKUs
    top_savings = ps.get("top_savings_skus", [])[:5]
    if top_savings:
        elements.append(Paragraph("Top 5 SKUs by Savings Opportunity", STYLES["heading"]))
        top_data = [["SKU", "Description", "Baseline", "Optimized", "Savings"]]
        for ts in top_savings:
            top_data.append([
                str(ts.get("part_id", "")),
                str(ts.get("description", ""))[:40],
                _rate_pct(ts.get("baseline_rate")),
                _rate_pct(ts.get("optimized_rate")),
                _rate_pct(ts.get("savings")),
            ])
        top_table = _styled_table(top_data, col_widths=[60, 200, 70, 70, 70])
        elements.append(top_table)
        elements.append(Spacer(1, 14))

    # Duty exposure by overlay type
    elements.append(Paragraph("Duty Exposure by Type", STYLES["heading"]))
    exposure_data = [
        ["Overlay Type", "Annual Exposure"],
        ["Base MFN Rate", _money(total_base_duty)],
        ["Section 301", _money(total_301_exposure)],
        ["Section 232", _money(total_232_exposure)],
        ["AD/CVD", _money(total_adcvd_exposure)],
        ["FTA Savings Applied", f"-{_money(total_fta_savings)}"],
    ]
    exposure_table = _styled_table(exposure_data, col_widths=[250, 260])
    elements.append(exposure_table)

    # -----------------------------------------------------------------------
    # Page 2: SKU Detail Table
    # -----------------------------------------------------------------------
    elements.append(PageBreak())
    elements.append(Paragraph("SKU Detail Table", STYLES["title"]))
    elements.append(Spacer(1, 8))

    detail_header = ["#", "Part ID", "Description", "Origin", "HTS Code",
                     "Base", "Total", "Opt.", "Status"]
    detail_data = [detail_header]

    for i, r in enumerate(sku_results):
        status = r.get("status", "UNKNOWN")
        bd = r.get("duty_breakdown", {})
        status_flag = "✓" if status == "OPTIMIZED" else ("⚠" if status == "BASELINE" else "✗")

        detail_data.append([
            str(i + 1),
            str(r.get("part_id", ""))[:10],
            str(r.get("description", ""))[:30],
            str(r.get("origin_country", ""))[:3],
            str(r.get("hts_code", ""))[:12],
            _rate_pct(bd.get("base_rate", r.get("baseline_duty_rate"))),
            _rate_pct(bd.get("total_rate", r.get("baseline_duty_rate"))),
            _rate_pct(r.get("optimized_duty_rate")),
            status_flag,
        ])

    detail_table = _styled_table(
        detail_data,
        col_widths=[20, 55, 130, 30, 72, 45, 45, 45, 30],
    )

    # Color-code status column
    for i, r in enumerate(sku_results, 1):
        status = r.get("status", "")
        if status == "OPTIMIZED":
            detail_table.setStyle(TableStyle([
                ("TEXTCOLOR", (-1, i), (-1, i), BRAND_SUCCESS),
            ]))
        elif "manual_review" in status.lower() if isinstance(status, str) else False:
            detail_table.setStyle(TableStyle([
                ("TEXTCOLOR", (-1, i), (-1, i), BRAND_WARNING),
            ]))
        elif status in ("ERROR", "FAILED"):
            detail_table.setStyle(TableStyle([
                ("TEXTCOLOR", (-1, i), (-1, i), BRAND_DANGER),
            ]))

    elements.append(detail_table)

    # -----------------------------------------------------------------------
    # Page 3: Recommendations
    # -----------------------------------------------------------------------
    elements.append(PageBreak())
    elements.append(Paragraph("Recommendations", STYLES["title"]))
    elements.append(Spacer(1, 8))

    # Group recommendations by action type
    immediate_wins: List[str] = []
    medium_term: List[str] = []
    professional_review: List[str] = []

    if portfolio_optimization:
        fta_util = portfolio_optimization.get("fta_utilization", [])
        for item in fta_util:
            immediate_wins.append(
                f"{item.get('part_id', 'SKU')} ({item.get('origin_country', '')}): "
                f"Claim {item.get('fta_treaty', 'FTA')} preference — "
                f"immediate savings of {_money(item.get('potential_savings', 0))}/year"
            )

        origin_shifts = portfolio_optimization.get("origin_shifts", [])
        for item in origin_shifts:
            medium_term.append(
                f"Shift {item.get('sku_count', 0)} SKUs from {item.get('from_country', '')} to "
                f"{item.get('to_country', '')}: saves {_money(item.get('annual_savings', 0))}/year"
            )

        risks = portfolio_optimization.get("risk_items", [])
        for item in risks:
            professional_review.append(
                f"{item.get('part_id', 'SKU')}: {item.get('reason', 'Requires review')}"
            )

    # Also auto-detect from SKU results
    for r in sku_results:
        status = r.get("status", "")
        bd = r.get("duty_breakdown", {})

        # FTA-eligible but not claimed
        if r.get("origin_country") in ("MX", "CA") and bd.get("fta_preference_pct", 0) > 0:
            if r.get("part_id") not in [f.split("(")[0].strip() for f in immediate_wins]:
                savings_amt = (r.get("value_usd", 0) or 0) * (bd.get("base_rate", 0) or 0) * \
                             bd.get("fta_preference_pct", 0) / 10000 * (r.get("annual_volume", 1) or 1)
                if savings_amt > 0:
                    immediate_wins.append(
                        f"{r.get('part_id', 'SKU')} from {r.get('origin_country', '')}: "
                        f"Claim USMCA preference — immediate savings of {_money(savings_amt)}/year "
                        f"with no supply chain changes, just paperwork"
                    )

        # AD/CVD exposure
        if bd.get("ad_duty_rate", 0) > 0 or bd.get("cvd_duty_rate", 0) > 0:
            ad_conf = bd.get("adcvd_confidence", "medium")
            if ad_conf == "low":
                professional_review.append(
                    f"{r.get('part_id', 'SKU')}: AD/CVD match confidence is low "
                    f"(broad prefix match) — verify scope with trade counsel"
                )

        # Manual review required
        if "manual_review" in str(status).lower():
            professional_review.append(
                f"{r.get('part_id', 'SKU')}: Specific/compound rate requires manual review"
            )

    # Render sections
    if immediate_wins:
        elements.append(Paragraph(
            "Immediate Wins (No Supply Chain Changes)", STYLES["heading"]
        ))
        elements.append(Paragraph(
            "FTA preferences you're not claiming, reclassifications within same heading:",
            STYLES["body_small"],
        ))
        for win in immediate_wins:
            elements.append(Paragraph(f"• {win}", STYLES["body"]))
        elements.append(Spacer(1, 10))

    if medium_term:
        elements.append(Paragraph(
            "Medium-Term Opportunities (Supplier Changes)", STYLES["heading"]
        ))
        elements.append(Paragraph(
            "Origin shifts to FTA-eligible countries, alternate sourcing:",
            STYLES["body_small"],
        ))
        for item in medium_term:
            elements.append(Paragraph(f"• {item}", STYLES["body"]))
        elements.append(Spacer(1, 10))

    if professional_review:
        elements.append(Paragraph(
            "Items Requiring Professional Review", STYLES["heading"]
        ))
        elements.append(Paragraph(
            "AD/CVD scope questions, compound rate products, classification disputes:",
            STYLES["body_small"],
        ))
        for item in professional_review:
            elements.append(Paragraph(f"• {item}", STYLES["body"]))
        elements.append(Spacer(1, 10))

    if not immediate_wins and not medium_term and not professional_review:
        elements.append(Paragraph(
            "No specific optimization recommendations at this time. "
            "All SKUs appear to be classified optimally.",
            STYLES["body"],
        ))

    # Build PDF
    def _on_page(canvas, doc):
        _add_header(canvas, doc, "Portfolio Summary")
        _add_footer(canvas, doc, proof_id)

    doc.build(elements, onFirstPage=_on_page, onLaterPages=_on_page)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Full Combined Report PDF
# ---------------------------------------------------------------------------
def generate_full_report_pdf(
    job_data: Dict[str, Any],
    sku_results: List[Dict[str, Any]],
    portfolio_optimization: Optional[Dict[str, Any]] = None,
) -> bytes:
    """Generate combined report: portfolio summary + all individual SKU dossiers.

    Concatenates the portfolio PDF with individual SKU dossier PDFs.
    For efficiency, we build everything in a single document.
    """
    buf = io.BytesIO()
    proof_id = job_data.get("proof_chain_id", job_data.get("job_id", "N/A"))

    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        topMargin=50, bottomMargin=50,
        leftMargin=40, rightMargin=40,
    )

    elements: List[Any] = []

    # --- Portfolio section ---
    elements.append(Paragraph("TEaaS Full Portfolio Report", STYLES["title"]))
    elements.append(Paragraph(
        f"Job: {job_data.get('job_id', 'N/A')} | "
        f"Date: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        STYLES["body_small"],
    ))
    elements.append(Spacer(1, 8))

    ps = job_data.get("portfolio_summary", {})
    elements.append(Paragraph("Executive Summary", STYLES["heading"]))

    summary_data = [
        ["Metric", "Value"],
        ["Total SKUs", str(ps.get("total_skus", len(sku_results)))],
        ["Total Baseline Duty", _money(ps.get("total_baseline_duty"))],
        ["Total Optimized Duty", _money(ps.get("total_optimized_duty"))],
        ["Total Savings", _money(ps.get("total_savings"))],
        ["Savings %", f"{ps.get('savings_percentage', 0) or 0:.1f}%"],
    ]
    elements.append(_styled_table(summary_data, col_widths=[250, 260]))
    elements.append(Spacer(1, 12))

    # SKU overview table
    elements.append(Paragraph("SKU Overview", STYLES["heading"]))
    overview_data = [["#", "Part ID", "Description", "Origin", "Base Rate", "Total Rate", "Status"]]
    for i, r in enumerate(sku_results):
        bd = r.get("duty_breakdown", {})
        overview_data.append([
            str(i + 1),
            str(r.get("part_id", ""))[:10],
            str(r.get("description", ""))[:35],
            str(r.get("origin_country", ""))[:3],
            _rate_pct(bd.get("base_rate", r.get("baseline_duty_rate"))),
            _rate_pct(bd.get("total_rate", r.get("baseline_duty_rate"))),
            r.get("status", "UNKNOWN"),
        ])
    elements.append(_styled_table(
        overview_data,
        col_widths=[20, 55, 160, 30, 60, 60, 80],
    ))

    # --- Individual SKU dossiers ---
    for r in sku_results:
        elements.append(PageBreak())
        part_id = r.get("part_id", "Unknown")
        elements.append(Paragraph(f"SKU Dossier — {part_id}", STYLES["title"]))
        elements.append(Spacer(1, 6))

        # Compact SKU info
        info_rows = [
            _info_row("Part ID", part_id),
            _info_row("Description", str(r.get("description", ""))[:80]),
            _info_row("Origin", str(r.get("origin_country", "N/A"))),
            _info_row("HTS Code", str(r.get("hts_code", "N/A"))),
        ]
        info_t = Table(info_rows, colWidths=[120, 380])
        info_t.setStyle(TableStyle([
            ("FONT", (0, 0), (-1, -1), "Helvetica", 8),
            ("BACKGROUND", (0, 0), (0, -1), BRAND_LIGHT),
            ("TOPPADDING", (0, 0), (-1, -1), 2),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ]))
        elements.append(info_t)
        elements.append(Spacer(1, 8))

        # Duty breakdown
        bd = r.get("duty_breakdown", {})
        duty_rows = [["Component", "Rate"]]
        duty_rows.append(["Base MFN", _rate_pct(bd.get("base_rate", r.get("baseline_duty_rate")))])
        if bd.get("section_232_rate", 0) > 0:
            duty_rows.append(["Sec 232", _rate_pct(bd["section_232_rate"])])
        if bd.get("section_301_rate", 0) > 0:
            duty_rows.append(["Sec 301", _rate_pct(bd["section_301_rate"])])
        if bd.get("ad_duty_rate", 0) > 0:
            duty_rows.append(["AD Duty", _rate_pct(bd["ad_duty_rate"])])
        if bd.get("fta_preference_pct", 0) > 0:
            duty_rows.append(["FTA", f"-{_rate_pct(bd['fta_preference_pct'])} on base"])
        duty_rows.append(["Total", _rate_pct(bd.get("total_rate", r.get("baseline_duty_rate")))])

        elements.append(_styled_table(duty_rows, col_widths=[200, 100]))

        if r.get("status") == "OPTIMIZED":
            elements.append(Spacer(1, 6))
            elements.append(Paragraph(
                f"Optimized rate: {_rate_pct(r.get('optimized_duty_rate'))} "
                f"(saves {_rate_pct((r.get('baseline_duty_rate', 0) or 0) - (r.get('optimized_duty_rate', 0) or 0))})",
                STYLES["body_bold"],
            ))

    # Build PDF
    def _on_page(canvas, doc):
        _add_header(canvas, doc, "Full Portfolio Report")
        _add_footer(canvas, doc, proof_id)

    doc.build(elements, onFirstPage=_on_page, onLaterPages=_on_page)
    return buf.getvalue()
